version: 0.2

phases:
  install:
    commands:
      # Update and install unzip, wget
      - apt-get update && apt-get install -y unzip wget
      # Check if Terraform is installed and matches the desired version, if not install/upgrade it
      - |
        TERRAFORM_VERSION="1.1.0"
        if terraform version | grep -q "Terraform v${TERRAFORM_VERSION}"; then
          echo "Terraform v${TERRAFORM_VERSION} is already installed."
        else
          echo "Installing/Upgrading Terraform to v${TERRAFORM_VERSION}."
          wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          unzip -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin/
          rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
        fi

  pre_build:
    commands:
      - terraform init

  build:
    commands:
      # Apply the Terraform plan from the file
      - terraform apply -auto-approve tfplan

  post_build:
    commands:
      - echo "Terraform apply completed."

cache:
  paths:
    - '.terraform/**/*'
