AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a VPC with 4 subnets, a route table, and a security group.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "VPC Configuration"
        Parameters:
          - VpcCidr
      - Label:
          default: "Subnet Configuration"
        Parameters:
          - Subnet1Cidr
          - Subnet2Cidr
          - Subnet3Cidr
          - Subnet4Cidr
      - Label:
          default: "Security Group Ingress IP Ranges"
        Parameters:
          - AllowedIpRange1
          - AllowedIpRange2

Parameters:
  VpcCidr:
    Description: The CIDR block for the VPC
    Type: String
    Default: '10.110.0.0/16'

  Subnet1Cidr:
    Description: The CIDR block for Subnet 1
    Type: String
    Default: '10.110.1.0/24'

  Subnet2Cidr:
    Description: The CIDR block for Subnet 2
    Type: String
    Default: '10.110.2.0/24'

  Subnet3Cidr:
    Description: The CIDR block for Subnet 3
    Type: String
    Default: '10.110.3.0/24'

  Subnet4Cidr:
    Description: The CIDR block for Subnet 4
    Type: String
    Default: '10.110.4.0/24'

  AllowedIpRange1:
    Description: Allowed IP Range for Security Group
    Type: String
    Default: '192.168.0.0/16'

  AllowedIpRange2:
    Description: Another Allowed IP Range for Security Group
    Type: String
    Default: '10.0.0.0/8'

Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-vpc"

  Subnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref Subnet1Cidr
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-subnet-1"

  Subnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref Subnet2Cidr
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-subnet-2"

  Subnet3:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref Subnet3Cidr
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-subnet-3"

  Subnet4:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref Subnet4Cidr
      AvailabilityZone: !Select [ 3, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-subnet-4"

  RouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-route-table"

  Subnet1RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref Subnet1
      RouteTableId: !Ref RouteTable

  Subnet2RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref Subnet2
      RouteTableId: !Ref RouteTable

  Subnet3RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref Subnet3
      RouteTableId: !Ref RouteTable

  Subnet4RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref Subnet4
      RouteTableId: !Ref RouteTable

  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security group for generic setup'
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-sg"
      SecurityGroupIngress:
        - IpProtocol: -1  # -1 means all protocols
          FromPort: -1    # -1 means all ports
          ToPort: -1      # -1 means all ports
          CidrIp: !Ref AllowedIpRange1
        - IpProtocol: -1  # -1 means all protocols
          FromPort: -1    # -1 means all ports
          ToPort: -1      # -1 means all ports
          CidrIp: !Ref AllowedIpRange2

Outputs:
  VpcId:
    Description: 'VPC ID'
    Value: !Ref VPC

  Subnet1Id:
    Description: 'Subnet 1 ID'
    Value: !Ref Subnet1

  Subnet2Id:
    Description: 'Subnet 2 ID'
    Value: !Ref Subnet2

  Subnet3Id:
    Description: 'Subnet 3 ID'
    Value: !Ref Subnet3

  Subnet4Id:
    Description: 'Subnet 4 ID'
    Value: !Ref Subnet4

  RouteTableId:
    Description: 'Route Table ID'
    Value: !Ref RouteTable

  SecurityGroupId:
    Description: 'Security Group ID'
    Value: !Ref SecurityGroup
